# Generated by Django 4.1.4 on 2023-01-17 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Descripcion', models.CharField(blank=True, max_length=15, null=True)),
                ('Horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Apellido', models.CharField(max_length=15)),
                ('Edad', models.PositiveIntegerField(blank=True, default=8, null=True)),
                ('Años_Antiguedad_institucion', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('Correo_Institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('Talento_Habilidad', models.CharField(blank=True, max_length=35, null=True)),
                ('Deporte_Actividad', models.CharField(blank=True, max_length=35, null=True)),
                ('Valores_que_te_identifican', models.CharField(blank=True, max_length=35, null=True)),
                ('Nombre_Acudiente', models.CharField(blank=True, max_length=45, null=True)),
                ('Correo_Acudiente', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono_Acudiente', models.IntegerField(blank=True, null=True)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Apellido', models.CharField(max_length=15)),
                ('Titulo', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Psicoorientacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Comentario_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Colsulta_tipo', models.CharField(max_length=15)),
                ('Compromiso_de_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Recurrente', models.BooleanField(default=False)),
                ('Proxima_cita', models.DateField(null=True)),
                ('Evidencias', models.ImageField(null=True, upload_to='PSICOLOGIA')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
                ('psicoorientador', models.ForeignKey(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.curso')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_Desempeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo_Uno_Competencia', models.CharField(blank=True, max_length=500, null=True)),
                ('Periodo_Uno_1', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Uno_2', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Uno_3', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_Competencia', models.CharField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_1', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_2', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_3', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_Competencia', models.CharField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_1', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_2', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_3', models.TextField(blank=True, max_length=500, null=True)),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.asignatura')),
                ('Grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Clasificacion', models.IntegerField(blank=[(1, 'No Aplica'), (2, 'Tipo 1'), (3, 'Tipo 2'), (4, 'Tipo 3')], choices=[(1, 'Academico'), (2, 'Emocional'), (3, 'Orientación'), (4, 'Enfermeria')])),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Comentario_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('FaltaTipo', models.IntegerField(blank=[(1, 'No Aplica'), (2, 'Tipo 1'), (3, 'Tipo 2'), (4, 'Tipo 3')], choices=[(1, 'No Aplica'), (2, 'Tipo 1'), (3, 'Tipo 2'), (4, 'Tipo 3')])),
                ('Compromiso_de_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Recurrente', models.BooleanField(default=False)),
                ('Cita_Acudientes', models.DateField(null=True)),
                ('Puntos_negativos', models.PositiveIntegerField(default=1)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
                ('Profesor', models.ForeignKey(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.grado'),
        ),
        migrations.CreateModel(
            name='Convivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Comentario_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('FaltaTipo', models.CharField(max_length=15)),
                ('Compromiso_de_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Recurrente', models.BooleanField(default=False)),
                ('Cita_Acudientes', models.DateField(null=True)),
                ('Puntos_negativos', models.PositiveIntegerField(default=1)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
                ('Profesor', models.ForeignKey(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_De_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.asignatura')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.curso')),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
