# Generated by Django 4.1.4 on 2023-01-16 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Descripcion', models.CharField(blank=True, max_length=15, null=True)),
                ('Horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Apellido', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Apellido', models.CharField(max_length=15)),
                ('Titulo', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_Desempeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo_Uno_Competencia', models.CharField(blank=True, max_length=500, null=True)),
                ('Periodo_Uno_1', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Uno_2', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Uno_3', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_Competencia', models.CharField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_1', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_2', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Dos_3', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_Competencia', models.CharField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_1', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_2', models.TextField(blank=True, max_length=500, null=True)),
                ('Periodo_Tres_3', models.TextField(blank=True, max_length=500, null=True)),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.asignatura')),
                ('Grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Comentario_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_De_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.asignatura')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.curso')),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
