# Generated by Django 4.1.4 on 2023-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='Evidencias',
            field=models.ImageField(null=True, upload_to='Historico'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Cita_Acudientes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
