# Generated by Django 4.1.4 on 2023-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0002_historico_evidencias_alter_historico_cita_acudientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='Evidencias',
            field=models.ImageField(null=True, upload_to='historico'),
        ),
    ]
