# Generated by Django 4.1.4 on 2023-01-16 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionDocente', '0002_historico_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='Profesor',
            field=models.ForeignKey(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Convivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Comentario_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('FaltaTipo', models.CharField(max_length=15)),
                ('Compromiso_de_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Recurrente', models.BooleanField(default=False)),
                ('Cita_Acudientes', models.DateField(null=True)),
                ('Puntos_negativos', models.PositiveIntegerField(default=1)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
                ('Profesor', models.ForeignKey(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
