# Generated by Django 4.1.4 on 2023-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0003_alter_historico_evidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Descripcion_patologias',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Patologia_alergias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Restaurante',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Media'), (3, 'Completa')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Ruta',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Media'), (3, 'Completa')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='Clasificacion',
            field=models.IntegerField(choices=[(1, 'Academico'), (2, 'Emocional'), (3, 'Orientación'), (4, 'Enfermeria')]),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Evidencias',
            field=models.ImageField(null=True, upload_to='historico/'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='FaltaTipo',
            field=models.IntegerField(choices=[(1, 'No Aplica'), (2, 'Tipo 1'), (3, 'Tipo 2'), (4, 'Tipo 3')]),
        ),
    ]
