# Generated by Django 4.1.4 on 2023-01-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0003_alter_historico_profesor_convivencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.curso'),
            preserve_default=False,
        ),
    ]
