# Generated by Django 4.1.4 on 2023-01-16 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionDocente', '0004_estudiante_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicoorientacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Comentario_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Colsulta_tipo', models.CharField(max_length=15)),
                ('Compromiso_de_Estudiante', models.TextField(blank=True, max_length=500, null=True)),
                ('Recurrente', models.BooleanField(default=False)),
                ('Proxima_cita', models.DateField(null=True)),
                ('Evidencias', models.ImageField(null=True, upload_to='PSICOLOGIA')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
                ('psicoorientador', models.ForeignKey(default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
