# Generated by Django 4.1.4 on 2023-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0004_estudiante_descripcion_patologias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Descripcion_patologias',
            new_name='Descripcion_patologias_o_alergia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Direccion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
