# Generated by Django 4.1.4 on 2023-01-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0005_rename_descripcion_patologias_estudiante_descripcion_patologias_o_alergia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
