# Generated by Django 4.1.4 on 2023-01-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0007_listas_nombre_lista_remove_listas_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_nota', models.PositiveIntegerField(default=1)),
                ('Descripcion', models.CharField(max_length=55)),
                ('Nota', models.PositiveIntegerField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.listas')),
                ('Estudiante', models.ManyToManyField(to='GestionDocente.estudiante')),
            ],
        ),
    ]
