# Generated by Django 4.1.4 on 2023-01-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0008_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Nota',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Numero_nota',
        ),
        migrations.AddField(
            model_name='notas',
            name='Español_1',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Español_2',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Español_3',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Español_4',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Matematicas_1',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Matematicas_2',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Matematicas_3',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='Matematicas_4',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Estudiante',
        ),
        migrations.AddField(
            model_name='notas',
            name='Estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante'),
            preserve_default=False,
        ),
    ]
