# Generated by Django 4.1.4 on 2023-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0011_notas_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='Clubhouse',
            field=models.IntegerField(choices=[(1, 'Robotica'), (2, 'cocoma'), (3, 'Ciencia con conciencia'), (4, 'Danza')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='Mensiones',
            field=models.IntegerField(choices=[(1, 'Academico'), (2, 'Emocional'), (3, 'Orientación')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notas',
            name='Español_1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Español_2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Español_3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Español_4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Matematicas_1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Matematicas_2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Matematicas_3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Matematicas_4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
    ]
