# Generated by Django 4.1.4 on 2023-01-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0012_notas_clubhouse_notas_mensiones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Español_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Español_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Español_3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Español_4',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Matematicas_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Matematicas_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Matematicas_3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Matematicas_4',
        ),
        migrations.AddField(
            model_name='notas',
            name='Asignatura',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.asignacion_de_curso'),
            preserve_default=False,
        ),
    ]
