# Generated by Django 4.1.4 on 2023-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0013_remove_notas_curso_remove_notas_español_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='Nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
