# Generated by Django 4.1.4 on 2023-01-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0014_notas_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamado_lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Comentario_Docente', models.TextField(blank=True, max_length=500, null=True)),
                ('Llego', models.BooleanField(default=False)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.estudiante')),
            ],
        ),
    ]
