# Generated by Django 4.1.4 on 2023-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0015_llamado_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamado_lista',
            name='Recurrente',
            field=models.BooleanField(default=False),
        ),
    ]
