# Generated by Django 4.1.4 on 2023-01-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocente', '0019_alter_historico_puntos_negativos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadores_desempeño',
            old_name='Periodo_Dos_Competencia',
            new_name='Periodo_Dos_Logro',
        ),
        migrations.RenameField(
            model_name='indicadores_desempeño',
            old_name='Periodo_Tres_Competencia',
            new_name='Periodo_Tres_Logro',
        ),
        migrations.RenameField(
            model_name='indicadores_desempeño',
            old_name='Periodo_Uno_Competencia',
            new_name='Periodo_Uno_Logro',
        ),
    ]
